# Generated by Django 5.2.4 on 2025-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('items', '0002_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount_percent',
        ),
        migrations.AddField(
            model_name='discount',
            name='items',
            field=models.ManyToManyField(related_name='discounts', to='items.item'),
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скидка в %, например 10.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
