# Generated by Django 5.2.4 on 2025-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='amount_percent',
        ),
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент налога, например 10.00', max_digits=5),
        ),
    ]
