# Generated by Django 5.2.4 on 2025-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_currency'),
        ('taxes', '0002_remove_tax_amount_percent_tax_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='items',
            field=models.ManyToManyField(related_name='taxes', to='items.item', verbose_name='Выберите товары'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание налога'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название налога'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент налога, например 10.00', max_digits=5, verbose_name='Процент налога'),
        ),
    ]
