# Generated by Django 5.2.4 on 2025-07-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD ($)'), ('eur', 'EUR (€)'), ('rub', 'RUB (₽)')], default='rub', max_length=3),
        ),
    ]
